{
    "branch": "master",
    "verifyConditions": {                                                                                                                             
        "path": "semantic-release-docker",
        "registryUrl": "docker.io"
    },             
    "plugins": [
        "commitizen",
        "@semantic-release/commit-analyzer",
        "@semantic-release/release-notes-generator",
        [
            "@semantic-release/changelog",
            {
                "changelogFile": "CHANGELOG.md",
                "changelogTitle": "# DeepSea Track Changelog"
            }
        ],
        [
            "@semantic-release/git",
            {
                "assets": [
                    "CHANGELOG.md"
                ]
            }
        ]
#      ,
#        "semantic-release-docker",
#        [
#            "@semantic-release/exec",
#            {
#                "prepareCmd": "docker build --build-arg DOCKER_GID=$$DOCKER_GID --build-arg DOCKER_UID=$DOCKER_UID -t mbari/deepsea-track ."
#            }
#        ],
    ]
#  ,
#    "publish": [
#        {
#            "path": "semantic-release-docker",
#            "name": "mbari/deepsea-track"
#         }
#    ]
}    
